
interface Gi0/0/0/0
   description R2:Gi0-0-0-0
   ipv4 address 10.12.0.1/24
   ipv6 address 2000:abcd:12::1/64
   no shut
!
interface Gi0/0/0/3
   description R4:Gi0-0-0-3
   ipv4 address 10.14.0.1/24
   ipv6 address 2000:abcd:14::1/64
   no shut
!
interface Loopback0
 ipv6 address abcd::1/128
 ipv4 address 172.0.0.1/32
!
router isis 1
 net 49.0001.0000.0000.0001.00
 lsp-password keychain ISIS-DB
 address-family ipv4 unicast
  metric-style wide
 !
 address-family ipv6 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
   metric 1
  !
  address-family ipv6 unicast
  metric 1
  !
 !

 interface Gi0/0/0/0
  circuit-type level-2-only
  point-to-point
  hello-password keychain ISIS-DB
  suppressed
  address-family ipv4 unicast
   metric 10
  !
  address-family ipv6 unicast
   metric 10
  !
 !

 interface Gi0/0/0/3
  circuit-type level-2-only
  point-to-point
  hello-password keychain ISIS-DB
  suppressed
  address-family ipv4 unicast
   metric 10
  !
  address-family ipv6 unicast
   metric 10
  !
 !


key chain ISIS-DB
 key 0
  accept-lifetime 00:00:00 september 01 2024 00:00:00 september 01 2025
  key-string clear abcd
  send-lifetime 00:00:00 september 01 2024 00:00:00 september 01 2025
  cryptographic-algorithm HMAC-MD5
 !
 key 1
  accept-lifetime 00:00:00 october 01 2024 infinite
  key-string clear abcd1
  send-lifetime 00:00:00 october 01 2024 infinite
  cryptographic-algorithm HMAC-MD5
 !
!
router isis 1
address-family ipv4 unicast
  mpls traffic-eng level-2-only
  mpls traffic-eng router-id 172.0.0.1
  root
mpls label range table 0 30100 30199
mpls traffic-eng reoptimize 60
mpls traffic-eng signalling advertise explicit-null
mpls traffic-eng auto-bw collect frequency 1
root
mpls traffic-eng

 interface Gi0/0/0/0
  !
!

 interface Gi0/0/0/3
  !
!

rsvp

 interface Gi0/0/0/0
  bandwidth percentage 100
 !
!

 interface Gi0/0/0/3
  bandwidth percentage 100
 !
!


root
interface tunnel-te 2
 description "Tunnel to 172.0.0.2"
 ipv4 unnumbered Loopback0
 priority 7 7
 signalled-bandwidth 100
 auto-bw
  auto-capacity
  min-clones 0
  max-clones 15
  nominal-bandwidth 100
  split-bandwidth 150
  merge-bandwidth 50
  overflow threshold 10 min 10 limit 1
  adjustment-threshold 10 min 10
  application 5
 destination 172.0.0.2
 path-option 1 dynamic
 !
!
root
interface tunnel-te 3
 description "Tunnel to 172.0.0.3"
 ipv4 unnumbered Loopback0
 priority 7 7
 signalled-bandwidth 100
 auto-bw
  auto-capacity
  min-clones 0
  max-clones 15
  nominal-bandwidth 100
  split-bandwidth 150
  merge-bandwidth 50
  overflow threshold 10 min 10 limit 1
  adjustment-threshold 10 min 10
  application 5
 destination 172.0.0.3
 path-option 1 dynamic
 !
!
root
interface tunnel-te 4
 description "Tunnel to 172.0.0.4"
 ipv4 unnumbered Loopback0
 priority 7 7
 signalled-bandwidth 100
 auto-bw
  auto-capacity
  min-clones 0
  max-clones 15
  nominal-bandwidth 100
  split-bandwidth 150
  merge-bandwidth 50
  overflow threshold 10 min 10 limit 1
  adjustment-threshold 10 min 10
  application 5
 destination 172.0.0.4
 path-option 1 dynamic
 !
!