set interfaces lo0 unit 0 family inet address 172.0.0.5/32
set interfaces lo0 unit 0 family inet6 address abcd::5/128
set routing-options router-id 172.0.0.5

set interfaces ge-0/0/1 unit 0 family inet address 10.56.0.5/24
set interfaces ge-0/0/1 unit 0 family inet6 address 2000:abcd:56::5/64
set interfaces ge-0/0/1 unit 0 family iso
set interfaces ge-0/0/1 unit 0 family mpls
set interfaces ge-0/0/2 unit 0 family inet address 10.45.0.5/24
set interfaces ge-0/0/2 unit 0 family inet6 address 2000:abcd:45::5/64
set interfaces ge-0/0/2 unit 0 family iso
set interfaces ge-0/0/2 unit 0 family mpls


set system license keys key "JUNOS892191212 aeaqie alakap hs6c2a eqaaad 5adsqo zm7quo 3hqrmy hg74fs lzcbra wvagfc zxvq7a nwwdy2 63hajk u26llp mbk4wv sidbdz"
set routing-options autonomous-system 100
set protocols bgp group v4-mesh type internal
set protocols bgp group v4-mesh family inet unicast
set protocols bgp group v4-mesh peer-as 100
set protocols bgp group v4-mesh local-address 172.0.0.5
set protocols bgp group v6-mesh type internal
set protocols bgp group v6-mesh family inet6 unicast
set protocols bgp group v6-mesh peer-as 100
set protocols bgp group v6-mesh local-address abcd::5

set protocols bgp group v4-mesh neighbor 172.0.0.6
set protocols bgp group v6-mesh neighbor abcd::6

set protocols bgp group v4-mesh neighbor 172.0.0.4
set protocols bgp group v6-mesh neighbor abcd::4
